# Generated by Django 5.0.6 on 2025-08-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0021_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
