# Generated by Django 5.2.5 on 2025-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0007_remove_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
