# Generated by Django 5.2.5 on 2025-08-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0008_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
